version: "3.7"
services:
  app:
    restart: always
    container_name: "app"
    image: app
    environment:
      - MONGODB_URL=mongodb://mongo_db/nodes
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    networks:
      - custom
    depends_on:
      - mongo_db

  # database service
  mongo_db:
    restart: always
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db  
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  mongodb: